name: rolex-env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.13.7
  - numpy=2.3.3
  - pandas=2.3.2
  - matplotlib=3.10.6
  - seaborn=0.13.2
  - scipy=1.16.1
  - statsmodels=0.14.5
  - scikit-learn=1.7.1
  - sqlite=3.50.2
  - pip
  - pip:
    - matplotlib-inline 0.1.7
